// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ojlywntaeejmozwdwloe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9qbHl3bnRhZWVqbW96d2R3bG9lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3NDAzMDYsImV4cCI6MjA1OTMxNjMwNn0.WpDhJt0p_y1FAVfQMUaH0a8nn3hM0QidxmDY7YfC-ko";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);